language: python
sudo: false
cache:
  - pip
services:
  - memcached
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DJANGO="Django<1.9,>=1.8"
    - DJANGO="Django<1.10,>=1.9"
    - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
  - pip install --upgrade pip
  - pip install -r requirements_dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]] || [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install python-memcached; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] || [[ $TRAVIS_PYTHON_VERSION == pypy3 ]]; then pip install python3-memcached; fi
  - pip install $DJANGO
  - pip install coveralls
  - sh -e /etc/init.d/xvfb start
script:
  - isort --check-only --recursive --diff .
  - flake8 --jobs=2 .
  - pep257 django_select2
  - coverage run --source=django_select2 py.test
after_success:
  - coveralls
