language: python
sudo: false
cache:
- apt
- pip
services:
- memcached
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - python3-enchant
    - python2-enchant
    - graphviz
env:
  global:
  - DISPLAY=:99.0
  matrix:
  - DJANGO="Django<1.9,>=1.8"
  - DJANGO="Django<1.10,>=1.9"
  - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
- pip install --upgrade pip
- pip install -r requirements_dev.txt
- if [[ $TRAVIS_PYTHON_VERSION == 2* ]] || [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
  pip install python-memcached; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3* ]] || [[ $TRAVIS_PYTHON_VERSION == pypy3 ]];
  then pip install python3-memcached; fi
- pip install $DJANGO
- pip install coveralls
- sh -e /etc/init.d/xvfb start
script:
- isort --check-only --recursive --diff .
- flake8 --jobs=2 .
- pep257 --explain --source --count django_select2
- "(cd docs; make spelling)"
- coverage run --source=django_select2 -m py.test
after_success:
- coveralls
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: fEP9K7y0ZF9fRvQEUN4kgPXQEZvi3Cx3ikUebG2UM/2uhcaUQm0+KpgZ2S+lvOTYcBnNgzPzFsVIZMcVcTxwIKuQDEMq9y2eop2hnisb9KXsIm9qPYSzOnRm74VuiOt4hNOZMe0qVBK2cO3vC9NDXuzdI8A0JynJhthfl4t+kFM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: applegrew/django-select2
