language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DJANGO="<1.5,>=1.4"
    - DJANGO="<1.7,>=1.6"
    - DJANGO="<1.8,>=1.7"
    - DJANGO="==1.8rc1"
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="<1.5,>=1.4"
    - python: "3.3"
      env: DJANGO="<1.5,>=1.4"
    - python: "3.4"
      env: DJANGO="<1.5,>=1.4"
    - python: "pypy3"
      env: DJANGO="<1.5,>=1.4"
    - python: "2.6"
      env: DJANGO="<1.8,>=1.7"
  allow_failures:
    - env: DJANGO="==1.8rc1"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "pypy3"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install -r requirements_dev.txt
  - pip install Django$DJANGO
  - pip install coveralls
  - sh -e /etc/init.d/xvfb start
script:
  - isort -c -vb -rc ./django_select2
  - coverage run --source=django_select2 runtests.py
after_success:
  coveralls
