name: ✨ Feature
description: Request an enhancement.
body:

  - type: markdown
    attributes:
      value: |
        ## Discussions

        This project uses GitHub Discussions for feature requests.
        Please use the [Ideas Section](https://github.com/codingjoe/django-select2/discussions/categories/ideas) to discuss your idea with the community.
